// 0 - turn the rule off
const OFF = 0;
// 1 - turn the rule on as a warning (doesn't affect exit code)
const WARN = 1;
// 2 - turn the rule on as an error (exit code is 1 when triggered)
const ERROR = 2;

module.exports = {

	parserOptions: {
		ecmaVersion: 6,
		sourceType: 'module',
	},

	env: {
		'es6': true,
	},

	globals: {

	},

	rules: {
		// Possible Errors
		'comma-dangle': [ERROR, 'always-multiline'],
		'no-cond-assign': [ERROR],
		'no-console': [ERROR],
		'no-constant-condition': [ERROR],
		'no-control-regex': [OFF],
		'no-debugger': [ERROR],
		'no-dupe-args': [ERROR],
		'no-dupe-keys': [ERROR],
		'no-duplicate-case': [ERROR],
		'no-empty': [ERROR],
		'no-empty-character-class': [OFF],
		'no-ex-assign': [OFF],
		'no-extra-boolean-cast': [ERROR],
		'no-extra-parens': [OFF],
		'no-extra-semi': [ERROR],
		'no-func-assign': [OFF],
		'no-inner-declarations': [ERROR],
		'no-invalid-regexp': [ERROR],
		'no-irregular-whitespace': [ERROR],
		'no-negated-in-lhs': [OFF],
		'no-obj-calls': [OFF],
		'no-prototype-builtins': [OFF],
		'no-regex-spaces': [OFF],
		'no-sparse-arrays': [ERROR],
		'no-unexpected-multiline': [OFF],
		'no-unreachable': [ERROR],
		'no-unsafe-finally': [OFF],
		'use-isnan': [ERROR],
		'valid-jsdoc': [OFF],
		'valid-typeof': [ERROR],
		// Best Practices
		'accessor-pairs': [OFF],
		'array-callback-return': [ERROR],
		'block-scoped-var': [OFF],
		'complexity': [ERROR, 15],
		'consistent-return': [OFF],
		'curly': [ERROR, 'all'],
		'default-case': [OFF],
		'dot-location': [ERROR, 'property'],
		'dot-notation': [ERROR],
		'eqeqeq': [ERROR],
		'guard-for-in': [OFF],
		'no-alert': [ERROR],
		'no-caller': [OFF],
		'no-case-declarations': [ERROR],
		'no-div-regex': [OFF],
		'no-else-return': [OFF],
		'no-empty-function': [ERROR],
		'no-empty-pattern': [OFF],
		'no-eq-null': [OFF],
		'no-eval': [ERROR],
		'no-extend-native': [OFF],
		'no-extra-bind': [OFF],
		'no-extra-label': [OFF],
		'no-fallthrough': [OFF],
		'no-floating-decimal': [ERROR],
		'no-implicit-coercion': [ERROR],
		'no-implicit-globals': [OFF],
		'no-implied-eval': [OFF],
		'no-invalid-this': [OFF],
		'no-iterator': [OFF],
		'no-labels': [OFF],
		'no-lone-blocks': [ERROR],
		'no-loop-func': [ERROR],
		'no-magic-numbers': [OFF],
		'no-multi-spaces': [ERROR, {
			'exceptions': {
				'Property': true,
				'ObjectExpression': true,
			},
		}],
		'no-multi-str': [OFF],
		'no-native-reassign': [OFF],
		'no-new': [OFF],
		'no-new-func': [OFF],
		'no-new-wrappers': [OFF],
		'no-octal': [OFF],
		'no-octal-escape': [OFF],
		'no-param-reassign': [OFF],
		'no-proto': [OFF],
		'no-redeclare': [ERROR],
		'no-return-assign': [OFF],
		'no-script-url': [OFF],
		'no-self-assign': [OFF],
		'no-self-compare': [OFF],
		'no-sequences': [OFF],
		'no-throw-literal': [ERROR],
		'no-unmodified-loop-condition': [OFF],
		'no-unused-expressions': [ERROR],
		'no-unused-labels': [OFF],
		'no-useless-call': [OFF],
		'no-useless-concat': [OFF],
		'no-useless-escape': [OFF],
		'no-void': [OFF],
		'no-warning-comments': [OFF],
		'no-with': [ERROR],
		'radix': [ERROR, 'always'],
		'vars-on-top': [OFF],
		'wrap-iife': [OFF],
		'yoda': [OFF],
		// Strict Mode
		'strict': [OFF],
		// Variables
		'init-declarations': [OFF],
		'no-catch-shadow': [OFF],
		'no-delete-var': [OFF],
		'no-label-var': [OFF],
		'no-restricted-globals': [OFF],
		'no-shadow': [OFF],
		'no-shadow-restricted-names': [OFF],
		'no-undef': [ERROR],
		'no-undef-init': [OFF],
		'no-undefined': [OFF],
		'no-unused-vars': [ERROR],
		'no-use-before-define': [OFF],
		// Node.js and CommonJS
		'callback-return': [OFF],
		'global-require': [OFF],
		'handle-callback-err': [OFF],
		'no-mixed-requires': [OFF],
		'no-new-require': [OFF],
		'no-path-concat': [OFF],
		'no-process-env': [OFF],
		'no-process-exit': [OFF],
		'no-restricted-modules': [OFF],
		'no-sync': [OFF],
		// Stylistic Issues
		'array-bracket-spacing': [ERROR, 'never'],
		'block-spacing': [ERROR, 'always'],
		'brace-style': [ERROR, '1tbs', {
			'allowSingleLine': false,
		}],
		'camelcase': [ERROR, {
			'properties': 'never',
		}],
		'comma-spacing': [ERROR, {
			'before': false,
			'after': true,
		}],
		'comma-style': [ERROR, 'last'],
		'computed-property-spacing': [ERROR, 'never'],
		'consistent-this': [WARN, 'self'],
		'eol-last': [WARN],
		'func-names': [OFF],
		'func-style': [ERROR, 'declaration'],
		'id-blacklist': [OFF],
		'id-length': [OFF],
		'id-match': [OFF],
		'indent': [ERROR, 'tab', {
			'SwitchCase': 1,
		}],
		'jsx-quotes': [OFF],
		'key-spacing': [ERROR, {
			'singleLine': {
				'beforeColon': false,
				'afterColon': true,
				'mode': 'minimum',
			},
			'multiLine': {
				'beforeColon': false,
				'afterColon': true,
				'mode': 'strict',
			},
		}],
		'keyword-spacing': [ERROR, {
			'before': true,
			'after': true,
		}],
		'linebreak-style': [OFF],
		'lines-around-comment': [OFF],
		'max-depth': [ERROR, {
			'max': 4,
		}],
		'max-len': [OFF],
		'max-nested-callbacks': [OFF],
		'max-params': [OFF],
		'max-statements': [OFF],
		'max-statements-per-line': [ERROR, {
			'max': 1,
		}],
		'new-cap': [ERROR, {
			'newIsCap': true,
			'capIsNew': false,
		}],
		'new-parens': [ERROR],
		'newline-after-var': [OFF],
		'newline-before-return': [OFF],
		'newline-per-chained-call': [OFF],
		'no-array-constructor': [OFF],
		'no-bitwise': [OFF],
		'no-continue': [OFF],
		'no-inline-comments': [OFF],
		'no-lonely-if': [ERROR],
		'no-mixed-spaces-and-tabs': [OFF],
		'no-multiple-empty-lines': [ERROR],
		'no-negated-condition': [ERROR],
		'no-nested-ternary': [ERROR],
		'no-new-object': [OFF],
		'no-plusplus': [OFF],
		'no-restricted-syntax': [OFF],
		'no-spaced-func': [ERROR],
		'no-ternary': [OFF],
		'no-trailing-spaces': [ERROR],
		'no-underscore-dangle': [OFF],
		'no-unneeded-ternary': [ERROR],
		'no-whitespace-before-property': [OFF],
		'object-curly-spacing': [ERROR, 'always'],
		'object-property-newline': [OFF],
		'one-var': [ERROR, {
			'uninitialized': 'always',
			'initialized': 'never',
		}],
		'one-var-declaration-per-line': [ERROR, 'initializations'],
		'operator-assignment': [OFF],
		'operator-linebreak': [OFF],
		'padded-blocks': [OFF],
		'quote-props': [ERROR, 'consistent-as-needed'],
		'quotes': [ERROR, 'single', {
			'avoidEscape': false,
			'allowTemplateLiterals': false,
		}],
		'require-jsdoc': [OFF],
		'semi': [ERROR, 'always'],
		'semi-spacing': [ERROR, {
			'before': false,
			'after': true,
		}],
		'sort-vars': [OFF],
		'space-before-blocks': [ERROR],
		'space-before-function-paren': [ERROR, 'always'],
		'space-in-parens': [ERROR, 'never'],
		'space-infix-ops': [ERROR],
		'space-unary-ops': [ERROR, {
			'words': true,
			'nonwords': false,
		}],
		'spaced-comment': [OFF],
		'unicode-bom': [OFF],
		'wrap-regex': [OFF],
		// ES2015
		'arrow-body-style': [OFF],
		'arrow-parens': [ERROR, 'always'],
		'arrow-spacing': [ERROR, {
			'before': true,
			'after': true,
		}],
		'constructor-super': [ERROR],
		'generator-star-spacing': [OFF],
		'no-class-assign': [OFF],
		'no-confusing-arrow': [OFF],
		'no-const-assign': [ERROR],
		'no-dupe-class-members': [ERROR],
		'no-duplicate-imports': [OFF],
		'no-new-symbol': [OFF],
		'no-restricted-imports': [OFF],
		'no-this-before-super': [ERROR],
		'no-useless-computed-key': [OFF],
		'no-useless-constructor': [OFF],
		'no-useless-rename': [OFF],
		'no-var': [OFF],
		'object-shorthand': [OFF],
		'prefer-arrow-callback': [OFF],
		'prefer-const': [OFF],
		'prefer-reflect': [OFF],
		'prefer-rest-params': [ERROR],
		'prefer-spread': [ERROR],
		'prefer-template': [OFF],
		'require-yield': [OFF],
		'sort-imports': [OFF],
		'template-curly-spacing': [OFF],
		'yield-star-spacing': [OFF],
	},

};
