module.exports = {
	rules: {
		// Possible Errors
		'comma-dangle': ['error', 'always-multiline'],
		'no-cond-assign': ['error'],
		'no-console': ['error'],
		'no-constant-condition': ['error'],
		'no-control-regex': ['off'],
		'no-debugger': ['error'],
		'no-dupe-args': ['error'],
		'no-dupe-keys': ['error'],
		'no-duplicate-case': ['error'],
		'no-empty': ['error'],
		'no-empty-character-class': ['off'],
		'no-ex-assign': ['off'],
		'no-extra-boolean-cast': ['error'],
		'no-extra-parens': ['off'],
		'no-extra-semi': ['error'],
		'no-func-assign': ['off'],
		'no-inner-declarations': ['error'],
		'no-invalid-regexp': ['error'],
		'no-irregular-whitespace': ['error'],
		'no-negated-in-lhs': ['off'],
		'no-obj-calls': ['off'],
		'no-prototype-builtins': ['off'],
		'no-regex-spaces': ['off'],
		'no-sparse-arrays': ['error'],
		'no-unexpected-multiline': ['off'],
		'no-unreachable': ['error'],
		'no-unsafe-finally': ['off'],
		'use-isnan': ['error'],
		'valid-jsdoc': ['off'],
		'valid-typeof': ['error'],
	},
};
