module.exports = {
	rules: {
		// ES2015
		'arrow-body-style': ['off'],
		'arrow-parens': ['error', 'always'],
		'arrow-spacing': ['error', {
		  before: true,
		  after: true,
		}],
		'constructor-super': ['error'],
		'generator-star-spacing': ['off'],
		'no-class-assign': ['off'],
		'no-confusing-arrow': ['off'],
		'no-const-assign': ['error'],
		'no-dupe-class-members': ['error'],
		'no-duplicate-imports': ['off'],
		'no-new-symbol': ['off'],
		'no-restricted-imports': ['off'],
		'no-this-before-super': ['error'],
		'no-useless-computed-key': ['off'],
		'no-useless-constructor': ['off'],
		'no-useless-rename': ['off'],
		'no-var': ['off'],
		'object-shorthand': ['off'],
		'prefer-arrow-callback': ['off'],
		'prefer-const': ['off'],
		'prefer-reflect': ['off'],
		'prefer-rest-params': ['error'],
		'prefer-spread': ['error'],
		'prefer-template': ['off'],
		'require-yield': ['off'],
		'sort-imports': ['off'],
		'template-curly-spacing': ['off'],
		'yield-star-spacing': ['off'],
	},
};
